apps/verification/urls.py
from django.urls import path

from apps.verification.views import CreateVerificationRequest, ListOffice

urlpatterns = [
    path('', ListOffice.as_view()),
    path('crear-solicitud/', CreateVerificationRequest.as_view()),
]

sisvan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'SISVAN'

urlpatterns = [
                  path('', include('apps.verification.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

apps/system/models.py
from django.contrib.auth.models import User
from django.db import models
from django_tenants.models import TenantMixin, DomainMixin


class Offices(TenantMixin):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, null=True, blank=True)
    address = models.TextField(null=True, blank=True, verbose_name='Dirección')
    paid_until = models.DateField()
    on_trial = models.BooleanField()
    users = models.ManyToManyField(User, null=True, blank=True, verbose_name='Usuarios')
    created_on = models.DateField(auto_now_add=True)

    auto_create_schema = True

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'sys_oficinas'
        verbose_name_plural = 'Oficinas'
        verbose_name = 'Oficina'


class DomainOffice(DomainMixin):
    class Meta:
        db_table = 'sys_dominios'
        verbose_name = 'Sitio web'
        verbose_name_plural = 'Sitios web'


# class AttentionSettings(models.Model):
#     WEEKDAY = (
#         ('D', 'Domingo'),
#         ('L', 'Lunes'),
#         ('M', 'Martes'),
#         ('E', 'Miercoles'),
#         ('J', 'Jueves'),
#         ('V', 'Viernes'),
#         ('S', 'Sabado')
#     )
#     NUMBERS = (
#         ('0', '0'),
#         ('1', '1'),
#         ('2', '2'),
#         ('3', '3'),
#         ('4', '4'),
#         ('5', '5'),
#         ('6', '6'),
#         ('7', '7'),
#         ('8', '8'),
#         ('9', '9'),
#     )
#     weekday = models.CharField(max_length=1, choices=WEEKDAY, verbose_name='Día de la semana')
#     final_number_one = models.CharField(max_length=1, choices=NUMBERS, verbose_name='Terminal de cédula 1')
#     final_number_two = models.CharField(max_length=1, verbose_name='Terminal de cédula 2')
#
#     class Meta:
#         db_table = 'sys_attention_settings'
#         verbose_name = 'Configuración de terminal de cédula'
#         verbose_name_plural = 'Configuraciones de terminal de cédula'

apps/verification/models.py
import datetime as _date
from django.db import models
from django.utils.safestring import mark_safe
from django_softdelete.models import SoftDeleteModel


class Applicant(SoftDeleteModel):
    identification_number = models.CharField(max_length=40, primary_key=True, verbose_name='Cédula de identidad')
    first_name = models.CharField(max_length=40, verbose_name='Primer nombre')
    second_name = models.CharField(max_length=40, null=True, blank=True, verbose_name='Segundo nombre')
    last_name = models.CharField(max_length=40, verbose_name='Primer apellido')
    mother_last_name = models.CharField(max_length=40, null=True, blank=True, verbose_name='Segundo apellido')
    email = models.EmailField(max_length=100, null=False, blank=False, verbose_name='Correo electrónico')
    phone = models.CharField(max_length=11, null=False, blank=False, verbose_name='Número de celular')

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        db_table = 'sys_applicant_verification'
        verbose_name = 'Solicitante'
        verbose_name_plural = 'Solicitantes'


class VerificationRequest(SoftDeleteModel):
    STATUS = (
        ('E', 'Es espera de verificación'),
        ('A', 'Aprobado'),
        ('R', 'Rechazado'),
        ('C', 'Es espera de aprobación por control previo'),
    )

    birth_certificate = models.FileField(upload_to='actas/', null=False, blank=False, verbose_name='Acta de nacimiento')
    application_date = models.DateField(default=_date.date.today, verbose_name='Fecha de la solicitud')
    status = models.CharField(
        max_length=1,
        choices=STATUS,
        default='E',
        verbose_name='Estatus de la solicitud')
    date_appointment = models.DateField(null=True, blank=True, verbose_name='Fecha de la cita')
    applicant = models.ForeignKey(Applicant, null=False, blank=True, on_delete=models.CASCADE,
                                  verbose_name='Solicitante')

    def __str__(self):
        return 'Solicitud #' + str(self.id)

    def nombre_solicitante(self):
        return self.applicant.first_name

    def apellido_solicitante(self):
        return self.applicant.last_name

    def acta(self):
        return mark_safe('<a href = "/media/' + str(
            self.birth_certificate) + '" target="_blank" class= "text-center"><img src = "/media/' + str(
            self.birth_certificate) + '" width="50"></a>')

    class Meta:
        db_table = 'sys_verification_request'
        verbose_name = 'Solicitud de verificación'
        verbose_name_plural = 'Solicitudes de verificación'
        ordering = ['application_date']

apps/verification/forms.py
from django import forms
from django.forms import FileInput
from apps.verification.models import VerificationRequest, Applicant


class FormRegistrationApplicant(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for campo in self.fields:
            if campo != 'birth_certificate' and campo != 'is_deleted':
                self.fields[campo].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Applicant
        fields = '__all__'


class FormCreateRequestVerification(forms.ModelForm):
    class Meta:
        model = VerificationRequest
        exclude = ['application_date', 'status', 'date_appointment']
        widgets = {
            'birth_certificate':
                FileInput(attrs={'class': 'd-none',
                                 'accept': 'image/*',
                                 'birth_certificate': 'certificate'})
        }

apps/system/views.py
from django.shortcuts import render

# Create your views here.

apps/verification/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from django_tenants.postgresql_backend.base import IntegrityError

from apps.system.models import DomainOffice
from apps.verification.forms import FormCreateRequestVerification, FormRegistrationApplicant
from apps.verification.models import VerificationRequest
from sisvan import settings


class CreateVerificationRequest(CreateView):
    model = VerificationRequest
    form_class = FormCreateRequestVerification
    form_applicant = FormRegistrationApplicant
    template_name = 'verification/request_verification.html'
    success_url = '/crear-solicitud/'

    def get_context_data(self, **kwargs):
        context = super(CreateVerificationRequest, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()

        if 'form_applicant' not in context:
            context['form_applicant'] = self.form_applicant()

        context['DOMAIN'] = settings.MAIN_DOMAIN

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST, request.FILES)
        form_applicant = self.form_applicant(request.POST, request.FILES)
        if not form.is_valid() or not form_applicant.is_valid():
            return render(request, self.template_name, self.get_context_data(form=form, form_applicant=form_applicant))

        # try:
        verification_request = form.save(commit=False)
        verification_request.applicant = form_applicant.save(commit=True)
        verification_request.save()
        messages.info(request, 'El envio de la solicitud de verificación se realizó con éxito.')
        return HttpResponseRedirect(self.success_url)

        # except IntegrityError:
        #     applicant = Applicant.objects.get(identification_number=request.POST.get('identification_number'))


class ListOffice(ListView):
    model = DomainOffice
    queryset = DomainOffice.objects.filter(tenant__on_trial=True)
    template_name = 'verification/selected_office.html'

    def get_context_data(self, **kwargs):
        context = super(ListOffice, self).get_context_data(**kwargs)

        context['DOMAIN'] = settings.MAIN_DOMAIN

        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <title>SISVAC</title>
</head>
<body>
<div class="container py-3">
    {% include 'partials/header.html' %}

    <main>
        {% block content %} {% endblock %}
    </main>

    <footer class="pt-4 my-md-5 pt-md-5 border-top"></footer>
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
{% block js %} {% endblock %}
</html>

templates/partials/header.html
{% load static %}
<header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-2 border-bottom">
        <a href="{{ DOMAIN }}" class="d-flex align-items-center text-dark text-decoration-none">
            <img src="{% static 'images/CNE_logo.svg' %}" width="80px">

        </a>
        <div class="d-inline-flex">
            <span class="fs-4 text-center">Sistema de verificación de actas de nacimiento</span>
        </div>

        <div class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <img src="{% static 'images/LOGOSAIME.jpg' %}" width="60px">
        </div>
    </div>


</header>
{% include 'show_message.html' %}

templates/show_message.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}: </strong><span>{{ error|escape }}</span>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}: </strong>
        </div>
    {% endfor %}
{% endif %}

{% if form_applicant.errors %}
    {% for field in form_applicant %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}: </strong><span>{{ error|escape }}</span>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form_applicant.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-info text-center" role="alert">
            {{ message }}
            {% block js %}
                <script>
                    setInterval(() => {
                        window.location.href = '{{ DOMAIN }}'
                    }, 3000);
                </script>
            {% endblock %}
        </div>
    {% endfor %}
{% endif %}

templates/verification/request_verification.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="container-fluid mt-5 pt-5 pb-5">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="row">
                <div class="col-md-8 col-sm-12">
                    <h4 class="text-center mb-5">Datos del padre o representante</h4>
                    <div class="row row-cols-2">
                        <div class="mb-3 col">
                            <label for="exampleInputEmail1" class="form-label">Número de Cédula (*)</label>
                            {{ form_applicant.identification_number }}
                        </div>
                        <div class="mb-3 col"></div>
                        <div class="mb-3 col">
                            <label for="exampleInputEmail1" class="form-label">Primer Nombre (*)</label>
                            {{ form_applicant.first_name }}
                        </div>
                        <div class="mb-3 col">
                            <label for="exampleInputEmail1" class="form-label">Primer Apellido (*)</label>
                            {{ form_applicant.last_name }}
                        </div>
                        <div class="mb-3 col">
                            <label for="exampleInputEmail1" class="form-label">Segundo Nombre</label>
                            {{ form_applicant.second_name }}
                            <div class="form-text">Campo Opcional</div>
                        </div>
                        <div class="mb-3 col">
                            <label for="exampleInputEmail1" class="form-label">Segundo Apellido</label>
                            {{ form_applicant.mother_last_name }}
                            <div class="form-text">Campo Opcional</div>
                        </div>
                    </div>
                    <fieldset class="mt-4">
                        <legend>Datos de contacto</legend>
                        <div class="row row-cols-2">
                            <div class="mb-3 col">
                                <label for="exampleInputEmail1" class="form-label">Correo eletrónico (*)</label>
                                {{ form_applicant.email }}
                            </div>
                            <div class="mb-3 col">
                                <label for="exampleInputEmail1" class="form-label">Número de celular (*)</label>
                                {{ form_applicant.phone }}
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="col-md-4 col-sm-12">
                    <h4 class="text-center">Clic en la imagen para cargar el acta de nacimiento</h4>
                    <div class="row justify-content-center">
                        <div class="col-6">
                            <img src="{% static 'images/image.svg' %}" style="width: 100%; cursor:pointer;"
                                 id="preview">
                            {{ form.birth_certificate }}
                        </div>
                    </div>
                </div>
            </div>

            {{ form.is_deleted }}
            {{ form_applicant.is_deleted }}

            <button class="w-100 btn btn-lg btn-primary mt-5">
                Enviar la solicitud
            </button>
        </form>
    </section>

{% endblock %}

{% block js %}
    <script>
        $('#preview').click(function () {
            $('#id_birth_certificate').trigger('click');
        });
        $('#id_birth_certificate').change(function () {
            const file = this.files[0];
            const objectURL = URL.createObjectURL(file);
            $('#preview').attr('src', objectURL);
        });
    </script>
{% endblock %}

templates/verification/selected_office.html
{% extends 'base.html' %}

{% block content %}
    <div class="pricing-header p-3 pt-5 pb-md-5 mx-auto text-center">
        <h1 class="display-4 fw-normal">Seleccione una oficina</h1>
        <p class="fs-5 text-muted">
            Por favor seleccione la oficina más cerca a su domicilio
        </p>
    </div>

    <div class="row row-cols-sm-2 row-cols-md-3 mb-3 text-center justify-content-center">
        {% for domain in object_list %}
            <div class="col">
                <div class="card mb-5 rounded-4 shadow-sm">
                    <div class="card-header py-3">
                        <h3 class="my-0 fw-normal text-center">{{ domain.tenant.name }}</h3>
                    </div>
                    <div class="card-body">
                        <p class="card-title pricing-card-title">
                            Dirección
                        </p>
                        <p class="text-start">
                            <small class="text-muted fw-light">{{ domain.tenant.address }}</small>
                        </p>
                        <a href="http://{{ domain.domain }}/crear-solicitud/" class="w-100 btn btn-lg btn-outline-primary">
                            Ingresar
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}